game_store/authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
]

game_store/basketapp/urls.py
import basketapp.views as basketapp
from django.urls import path, include

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/<int:game_id>/', basketapp.add, name='add'),
    path('remove/<int:game_basket_id>/', basketapp.remove, name='remove'),
]

game_store/game_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='mainapp')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', admin.site.urls),
]

game_store/mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('genre/', mainapp.genre, name='genre'),
    path('genre/category/<int:category_pk>/', mainapp.genre_section, name='genre_section'),
    path('genre/game/<int:game_pk>/', mainapp.game_page, name='game_page'),

    path('genre/create/', mainapp.add_genre, name='add_genre'),
    path('genre/edit/<int:pk>/', mainapp.edit_genre, name='edit_genre'),
    path('genre/remove/<int:pk>/', mainapp.delete_genre, name='delete_genre'),

    path('genre/game/add/', mainapp.add_game, name='add_game'),
    path('genre/edit/game/<int:pk>/', mainapp.edit_game, name='edit_game'),
    path('genre/remove/game/<int:pk>/', mainapp.delete_game, name='delete_game'),
]

game_store/mainapp/models.py
from django.contrib.auth.models import User
from django.db import models


class GameCategory(models.Model):
    name = models.CharField('Название', max_length=60)
    desc = models.TextField('Описание', blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Жанр игр'
        verbose_name_plural = 'Жанры игр'


class Game(models.Model):
    category = models.ForeignKey(GameCategory, on_delete=models.CASCADE, verbose_name='Жанр')
    name = models.CharField('Название', max_length=60)
    desc = models.TextField('Описание', blank=True)
    price = models.CharField('Цена', max_length=30)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Игра'
        verbose_name_plural = 'Игры'

game_store/mainapp/forms.py
from django import forms

from mainapp.models import GameCategory, Game


class CategoryForm(forms.ModelForm):
    class Meta:
        model = GameCategory
        fields = (
            'name',
            'desc',
        )


class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = (
            'category',
            'name',
            'desc',
            'price',
        )


class DeleteGenre(forms.ModelForm):
    class Meta:
        model = GameCategory
        fields = (
            'name',
            'desc',
        )

game_store/mainapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponseNotFound

from mainapp.forms import CategoryForm, GameForm, DeleteGenre
from mainapp.models import GameCategory, Game


@login_required()
def index(request):
    context = {
        'page_title': 'главная'
    }
    return render(request, 'mainapp/index.html', context)


def genre(request):
    categories = GameCategory.objects.all()
    context = {
        'categories': categories,
        'page_title': 'Жанры'
    }
    return render(request, 'mainapp/genre.html', context)


def genre_section(request, category_pk):
    items = Game.objects.filter(category_id=category_pk)
    context = {
        'items': items,
        'page_title': 'Страница жанра'
    }
    return render(request, 'mainapp/genre_section.html', context)


def game_page(request, game_pk):
    game = Game.objects.get(pk=game_pk)
    context = {
        'game': game,
        'page_title': 'Страница игры'
    }
    return render(request, 'mainapp/game_page.html', context)


def add_genre(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mainapp:genre'))
    else:
        form = CategoryForm()
    context = {
        'title': 'Добавить категорию',
        'form': form,
    }
    return render(request, 'mainapp/add_genre.html', context)


def edit_genre(request, pk):
    category = GameCategory.objects.get(id=pk)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mainapp:genre'))
    else:
        form = CategoryForm(instance=category)
    context = {
        'title': 'Изменить жанр',
        'form': form,
    }
    return render(request, 'mainapp/add_genre.html', context)


def delete_genre(request, pk):
    remove_genre = GameCategory.objects.get(id=pk)
    remove_genre.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def add_game(request):
    if request.method == 'POST':
        form = GameForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mainapp:genre'))
    else:
        form = GameForm()
    context = {
        'title': 'Добавить игру',
        'form': form,
    }
    return render(request, 'mainapp/add_game.html', context)


def edit_game(request, pk):
    game = Game.objects.get(id=pk)
    if request.method == 'POST':
        form = GameForm(request.POST, instance=game)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('mainapp:genre'))
    else:
        form = GameForm(instance=game)
    context = {
        'title': 'Изменить игру',
        'form': form,
    }
    return render(request, 'mainapp/add_game.html', context)


def delete_game(request, pk):
    remove_game = Game.objects.get(id=pk)
    remove_game.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

game_store/mainapp/templates/mainapp/add_category.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Добавить</button>
    </form>
</div>
{% endblock %}

game_store/mainapp/templates/mainapp/add_game.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success">Добавить игру</button>
    </form>
</div>
{% endblock %}

game_store/mainapp/templates/mainapp/add_genre.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-success">Добавить жанр</button>
    </form>
</div>
{% endblock %}

game_store/mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|default:"Главная"|capfirst }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% block menu %}
<nav>
    <ul class="topmenu">
        <li>
            <a href="{% url 'mainapp:index' %}">Главная</a>
        </li>
        <li>
            <a href="{% url 'mainapp:genre' %}" class="down">Жанры</a></li>
        <li>
            <a href="{% url 'basket:index' %}">Корзина</a>
        </li>
        <li class="nav-item">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'authapp:logout' %}">Выйти</a>

            {% else %}
            <a class="nav-link" href="{% url 'authapp:login' %}">Войти</a>
            {% endif %}
        </li>
    </ul>
</nav>
{% endblock %}
{% block content %}
{% endblock %}
</body>
</html>

game_store/mainapp/templates/mainapp/catalog_section.html
{% extends 'mainapp/base.html' %}
{% block content %}
<h1>Страница каталога</h1>
<div class="section-menu">
    <ul>
        {% for item in items %}
        <li>
            <h4><a href="{% url 'mainapp:game_page' item.pk %}">
                {{ item }}
            </a></h4>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

game_store/mainapp/templates/mainapp/game_page.html
{% extends 'mainapp/base.html' %}
{% block content %}
<h1>Игра: {{ game.name }}</h1>
    <p class="game_desc">
        <h5>Описание: {{ game.desc }}</h5>
    </p>
    <p class="game_price">
        <h5>Цена: {{ game.price }}</h5>
    </p>
    <a href="{% url 'basket:add' game.id %}"
        class="btn btn-dark">
        Купить
    </a>
{% endblock %}

game_store/mainapp/templates/mainapp/genre.html
{% extends 'mainapp/base.html' %}
{% block content %}
<h1>Жанры</h1>
<a class="btn btn-success" href="{% url 'mainapp:add_genre' %}">Добавить жанр</a>
<br>
<br>
<div class="genre-menu">
    <ul>
        {% for item in categories %}
        <li>
            <h4><a href="{% url 'mainapp:genre_section' item.pk %}">
                {{ item }}
            </a>
                <a href="{% url 'mainapp:edit_genre' item.pk %}" class="btn btn-info">
                    Редактировать
                </a>
                <a href="{% url 'mainapp:delete_genre' item.pk %}" class="btn btn-danger">
                    Удалить
                </a></h4>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

game_store/mainapp/templates/mainapp/genre_section.html
{% extends 'mainapp/base.html' %}
{% block content %}
<h1>Игры:</h1>
<a class="btn btn-success" href="{% url 'mainapp:add_game' %}">Добавить игру</a>
<div class="section-menu">
    <ul>
        {% for item in items %}
        <li>
            <h4><a href="{% url 'mainapp:game_page' item.pk %}">
                {{ item }}
            </a>
                <a href="{% url 'mainapp:edit_game' item.pk %}" class="btn btn-info">
                    Редактировать
                </a>
                <a href="{% url 'mainapp:delete_game' item.pk %}" class="btn btn-danger">
                    Удалить
                </a></h4>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

game_store/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% block content %}
{% endblock %}