game_store/authapp/urls.py
import authapp.views as authapp
from django.urls import path

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
]

game_store/basketapp/urls.py
import basketapp.views as basketapp
from django.urls import path, include

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add/<int:game_id>/', basketapp.add, name='add'),
    path('remove/<int:game_basket_id>/', basketapp.remove, name='remove'),
]

game_store/game_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainapp.urls', namespace='mainapp')),
    path('auth/', include('authapp.urls', namespace='authapp')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', admin.site.urls),
]

game_store/mainapp/urls.py
import mainapp.views as mainapp
from django.urls import path

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('genre/', mainapp.genre, name='genre'),
    path('genre/category/<int:category_pk>/', mainapp.genre_section, name='genre_section'),
    path('genre/game/<int:game_pk>/', mainapp.game_page, name='game_page'),

    path('genre/create/', mainapp.add_genre, name='add_genre'),
    path('genre/edit/<int:pk>/', mainapp.edit_genre, name='edit_genre'),
    path('genre/remove/<int:pk>/', mainapp.delete_genre, name='delete_genre'),

    path('genre/game/add/', mainapp.add_game, name='add_game'),
    path('genre/edit/game/<int:pk>/', mainapp.edit_game, name='edit_game'),
    path('genre/remove/game/<int:pk>/', mainapp.delete_game, name='delete_game'),
]

game_store/basketapp/models.py
from django.contrib.auth.models import User
from django.db import models

from mainapp.models import Game


class GameBasket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.added.strftime("%Y.%m.%d %H:%M")}: {self.game.name}'

    def to_html(self):
        return f'{self.added.strftime("%Y.%m.%d %H:%M")}: <b>{self.game.name}</b>'

game_store/basketapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

from django.urls import reverse

from basketapp.models import GameBasket
from mainapp.models import Game


def index(request):
    item = GameBasket.objects.filter(user=request.user)
    context = {
        'object_list': item,
    }
    return render(request, 'basketapp/basket.html', context)


def add(request, game_id):
    game = Game.objects.get(pk=game_id)
    GameBasket.objects.get_or_create(
        user=request.user,
        game=game
    )
    return HttpResponseRedirect(
        reverse('mainapp:genre_section',
                kwargs={'category_pk': game.category_id})
    )


def remove(request, game_basket_id):
    item = GameBasket.objects.get(id=game_basket_id)
    item.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

game_store/basketapp/templates/basketapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{{ page_title|capfirst }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
{% block menu %}
<nav>
    <ul class="topmenu">
        <li>
            <a href="{% url 'mainapp:index' %}">Главная</a>
        </li>
        <li>
            <a href="{% url 'mainapp:genre' %}" class="down">Жанры</a>
        </li>
        <li>
            <a href="{% url 'basket:index' %}">Корзина</a>
        </li>
        <li>
            {% if user.is_authenticated %}
            <a href="{% url 'authapp:logout' %}">Выйти</a>
            {% else %}
            <a href="{% url 'authapp:login' %}">Войти</a>
            {% endif %}
        </li>

    </ul>
</nav>
{% endblock %}
{% block content %}
{% endblock %}
</body>
</html>

game_store/basketapp/templates/basketapp/basket.html
{% extends 'basketapp/base.html' %}
{% block content %}
    <div class="basket">
        <h2>Корзина, {{user.username}}</h2>
        <ul>
            {% for item in object_list %}
                <li>
                    {{ item.to_html|safe}}
                    <a href="{% url 'basket:remove' item.pk %}" class="btn btn-danger">удалить</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}